#!/bin/bash
. /usr/lib/buildkit/buildkit_common.sh

NAME="BuildKit-Automatic-Packaging"
BASEDIR="/var/lib/buildkit"

buildkit_ensure_buildkit_directories /var/lib/buildkit/
buildkit_ensure_permissions 
buildkit_ensure_base_repo "${BASEDIR}/repo" "$NAME"
buildkit_ensure_apache "${BASEDIR}/repo"

